### ISSUE TITLE
I know this isn't really an open project or anything, but....

### ISSUE THREAD

**Issue by miramallows** [lazukr/ro-discord-bot#17] opened 2018-10-17 09:55 UTC
For like **weeks**, I've been trying to find someone who has made a discord.js bot with a reminder command, that doesn't have way too many commands (which would make it hard to understand/decipher) and has a database (most bots on here actually just use a Timeout function, which is ineffective as bots will go down either way) and _also uses similar dependencies as my bot_ (which I think you have, after glancing at your code). Either way, of course, I've been out of luck until today. 

(Please note that I've actually never learnt how to program and stuff... okay, you've been warned)

So basically my current bot has like maybe 30-40 really long commands which I haven't gotten around to cut up into diff. files yet through a command handler. I've tried using anidiotsguide command handler but I never really understood it, and the code just kept piling up.

So my questions are the following:

1) If I was to make a reminder command, how would I go about it based on your code?

2) If I had to make a reminder command...
(a) would it be best if I first used a basic command handler to chop it up first before making a reminder command?
(b) would you be willing to help out in answering extensive questions on the command?
(c) would you be willing to explain the theory behind some lines of your command?

3) What are the complete list of packages you used solely for reminder command?

Sorry for asking these questions. If you don't want to answer them, you can just close this issue.

**Comment by lazukr** [comment] 2018-10-18 03:46
Hi,

Before I begin, I would just say that my code in itself isn't very clean so it might be hard to read / understand it. However, I'll try my best to explain what happens. Furthermore, I might use terms / concepts that you aren't familiar with, in which case I suggest you search them up and see what they are about.

#### Background
All inputs with a command in discord will be pre processed such that the `args` parameter in any of my command files is an array of strings split on the spaces.  For example: If you send the following message `!command here are parameters`, the command's `args` parameter will be `["here", "are", "parameters"]`. 

#### How it works, kind of
1. My reminder function can be broken into several pieces. 

    * As part of what reminder does, I figured that you should be able to grab a list of them, prematurely cancel one if they aren't relevant anymore, completely wipe all reminders and of course, adding new reminders. To detect these sub-commands, I look at the 0th index in the `args` parameter. I also made sure to append the intended actions with `--` so that it's not something you can accidentally type. Thus, `--list`, `--remove`, `--clear`. If you do not specify any of these, it will assume you are planning to add a new reminder. 
    * In order to add a reminder, I require that the user specify a particular phrase at the end of their command arguments. Currently, it supports a `in` phrase, which is for a user to specify a relative time, from now, that they want the reminder to ping them. (e.g. !remind something **in 2 hours**, this would queue the reminder to occur 2 hours later). In order to capture this, I use [Regex](https://en.wikipedia.org/wiki/Regular_expression) to do so (If you need to play around with one use [this](https://regex101.com/) site to build your regex to work the way you want it). The important part is that Javascript has [`String.prototype.match()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/match) which allows you to capture a matching result in the first index of the array if there are any. Thus, I use Regex to check if the particular phrase exists, if so, continue on; otherwise, provide an error.
    * After that, I now have to figure out the amount of offset that the user provided. Using Regex above, you can grab these and filter them accordingly as well. (e.g. `/\\smin(ute)?(s)?/` will allow you to match something that is either `min`, `mins`, `minute` or `minutes`). After I have figured out the offset, I can simply add that to the current datetime. 
    * To queue this so the bot will actually send the message in offset time, I make use of [`node-schedule`](https://github.com/node-schedule/node-schedule#date-based-scheduling) to schedule the it. You can just refer that for anything regarding scheduling.
    * Lastly, to make it persistent data, I make use of [`node-persist`](https://github.com/simonlast/node-persist). Again, you can follow whatever they have their to get it to work. In order to ensure that one entry does not overwrite another entry, I made used of [`uuid`](https://github.com/kelektiv/node-uuid#readme) to generate unique IDs for me
    * All in all, this is very complicated to put into one command, thus in order to help with reusability and to keep it more separated from each other, I used two classes to help. `task-scheduler` is meant to handle all the scheduling related stuff while `task-factory` is meant to help create and process the task accordingly.
    * For the sake of readable to users, I also used [`moment`](https://github.com/moment/moment-timezone) to convert UTC timezone to their respective local timezone so they do not have to do the conversions themselves. 

2. 
    a. I'm not exactly sure what you mean here, but I figured that dealing with these sub-commands can be dealt relatively easily in the same "command" so they are all in the same place. 
    b. Sure
    c. Sure
3. 
    - [`node-schedule`](https://github.com/node-schedule/node-schedule#date-based-scheduling)
    - [`node-persist`](https://github.com/simonlast/node-persist)
    - [`uuid`](https://github.com/kelektiv/node-uuid#readme)
    - [`moment`](https://github.com/moment/moment-timezone)

**Comment by miramallows** [comment] 2018-10-20 08:26
Hi there,

Thank you for the time you took to reply to this.

I've tried to look through all of the coding again, but it still seems so confusing to me.

If I was to just make a very simple command that's just `!remind [items to remind] -in ss mm hh` would i still require regex?

**Comment by lazukr** [comment] 2018-10-20 15:47
Using Regex is not required. However, it helps you match a particular pattern of strings which can be useful in reducing the amount of cases you have to specifically handle as you can have it try matching for a particular pattern and if it doesn't match, throw a general error regarding it. I will list how I would probably have done it without Regex.

- Using `-in` to separate the message and the time is great. However you have to ensure it doesn't interfere with other usages of `-in` that may arise (e.g. `!remind do this -inside here -in ss mm hh`). Thus, a way to do so could be to split on the spaces to get an array and search backwards from the array for the first `-in`. The reason I suggest backwards is because then if someone uses `-in` by itself in the `[items to remind]` section, it doesn't accidentally grab that instead. 

- Once you have found the right `-in`, you can simply take the remaining amount of the array and treat them as your `ss mm hh`. It's up to you how you wish to handle extra parameters (e.g. assuming we are split on spaces, it would be `[ss, mm, hh]` normally. However, some people might put random text afterwards as well resulting in `[ss mm hh random random]`. You can either just ignore that or treat it as an invalid use case). Either way, you should be able to easily find where `ss mm hh` should be at.

- You will have to ensure there is proper conversion and filtering on `ss mm hh`. The best way I can think of right now is to do `parseInt()` on each of them (to try and make them integers), then check if they are within the range they belong in `ss/mm 0-59` and `hh 0-23`.

- Once you have done this, you can simply use `new Date()` to grab the current datetime and add the offsets individually. If you plan on using `node-schedule`, it allows you to pass in a date to schedule a job so that should be straightforward.

- If you still wish to store it into a database of some sort, again, I simply use `node-persist` since it's easy to use and set up. However, you can always look into more powerful solutions if you wish.

**Comment by miramallows** [comment] 2018-10-21 08:48
Hi there,

Thanks for the message! This was really informative, and I understood most of it. The only problem I have right now is that even after looking through docs, I don't really understand how `node-persist` works and how I can incorporate it with `node-schedule`. I'll be working on this though, and will ask when I have any other questions. Thank you for your time and patience :)

**Comment by miramallows** [comment] 2018-10-21 10:47
This is what I have right now (most of it is incorrect), but anyway.
```
const Discord = require('discord.js')
const schedule = require('node-schedule')
const moment = require('moment')
const prefix = process.env.PREFIX
exports.run = (client, message, args) => {
let cutuparg = message.content.slice(prefix.length).trim().split(" -in ")
let issue = cutuparg[0].split(" ").slice(1)
let time = cutuparg[1].split(" ")
let sstime = parseInt(time[0])
let mmtime = parseInt(time[1])
let hhtime = parseInt(time[2])
if(sstime < 60 && mmtime < 60 && hhtime < 24){
const duration = moment.duration({seconds: sstime, minutes: mmtime, hours: hhtime})
var date = moment().tz("America/Toronto").add(duration).format("YYYY, M, D, H, m, s")
message.channel.send(`orig date: ${date}`);
schedule.scheduleJob(date, function(issue){
message.member.send(issue);
})
const scheduledEmbed = new Discord.RichEmbed()
.setColor(process.env.basecolor)
.setDescription(`Okay, I'll remind you about ${issue} in ${hhtime}:${mmtime}:${sstime}`)
message.channel.send(scheduledEmbed);
}else{
return message.channel.send('invalid args');
}
}
```

**Comment by lazukr** [comment] 2018-11-04 17:03
Sorry for not replying for a while, I've been relatively busy. 

From what you have there, it seems you are on the right track. I hope you have gotten it to work. If not, we can go over any other issues you've encountered.

**Comment by miramallows** [comment] 2018-11-05 02:23
It doesn't work - it doesn't actually schedule it (makes the event occur). :P been waiting for your reply haha (and yes it's fine).

Not sure what I missed and why it doesn't work.

**Comment by lazukr** [comment] 2018-11-05 04:44
Okay, so I did some playing around. Here is the code I basically to test things out:
```Javascript
const scheduler = require('node-schedule');
const moment = require('moment');

const formatString = "YYYY, M, D, H, m, s";

const remind = (client, message, args) => {
  const cutuparg = args.split(" -in ");
  const issue = cutuparg[0].split(" ");
  const time = cutuparg[1].split(" ");
  const ss = parseInt(time[0]);
  const mm = parseInt(time[1]);
  const hh = parseInt(time[2]);

  if (ss < 60 && mm < 60 && hh < 24) {
    // get current datetime
    const now = moment();
    console.log(`Now date: ${now.format(formatString)}`);
    
    const duration = moment.duration({
      second: ss,
      minutes: mm,
      hours: hh,
    });

    const scheduled = moment(now).add(duration).tz("America/Toronto");
    const date = scheduled.format(formatString);
    
    console.log(`Scheduled date: ${date}`);
    scheduler.scheduleJob(scheduled.toDate(), () => {
      console.log(issue);
    });

  }
}; 

const client = {};
const message = {};

const args = "blah blah -in 05 00 0";

remind(client, message, args);
```
One thing you will note is that I separated `scheduled` vs `date`. This is because `scheduler.scheduleJob()` expects a [Date object](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date). Doing `moment().format(formatString)` converts it into a string, which isn't compatible. You will actually see that that I do `scheduled.toDate()` because again, momentjs does not give you a Date object, but rather a moment object, you need to convert it before using it.

The code above should work if you just run it on console. You'll have to wait 5 seconds before the issue is logged (as I've set it to be 5 seconds).

**Comment by miramallows** [comment] 2018-11-05 05:21
Ooof, yippee, that totally worked. Thanks so much. I

**Comment by miramallows** [comment] 2018-11-06 01:20
How do I incorporate node-persist?

**Comment by lazukr** [comment] 2018-11-06 04:20
I will go over a broad approach, how you end up doing it is up to you. Basically, you want to first have some sort of function that can read your persistent storage and queue up any reminders that were created and hasn't gone off yet. Then, in whatever function that adds the reminder to scheduler, also add it to the persistent storage. Finally, when the event occurs, have it also remove the scheduled item as well (you can skip this step and instead clean up any expired events on startup).

**Comment by miramallows** [comment] 2018-11-16 11:02
Hi! So after working on it for a few days, I've finally done it, thank you for your help! Due to the fact that I use sqlite for another thing, I decided to use sqlite since you were really broad about this and I realised that I could probably easily do it in sqlite. :D. The entire scheduled item thing sitll won't remove itself from db so I'll prolly add some code to delete expired events on event 'ready'. 

Thank you for all your help!

One thing I'm worried about is that maybe the date/time to remind might be right be when the bot sdudenly dies and restarts itself (mine does that sometimes), cuz my uptime is around 99.7% BUT there are in-between 1-2second downtimes... so rip that.

**Comment by lazukr** [comment] 2018-11-17 03:38
If you are afraid that you may have a reminder that is suppose to go off during the 1-2 second downtime, you can always have your bot go through each reminder in the database and if they are in the past, automatically trigger the reminder. Thus, it might be a bit delayed, but at least it will still happen.

**Comment by miramallows** [comment] 2018-11-17 08:50
problem is, i don't have an auto-delete from db yet

**Comment by lazukr** [comment] 2018-12-02 00:48
Closing this as I believe you know what to do now.

**Closed as completed by lazukr** 2018-12-02 00:48 UTC
